# Generated by Django 2.0 on 2019-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='unite',
            field=models.CharField(default='500g', max_length=20, verbose_name='商品单位'),
        ),
    ]
